-- connect to <DBNAME>;

set DB2MON.HIS_SNAPSHOT_TIMESTAMP = CURRENT TIMESTAMP;

INSERT INTO DB2MON.HIS_MON_BP_UTILIZATION
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_BP_UTILIZATION t;
INSERT INTO DB2MON.HIS_MON_CONNECTION_SUMMARY
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_CONNECTION_SUMMARY  t;
INSERT INTO DB2MON.HIS_MON_DB_SUMMARY
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_DB_SUMMARY t;
INSERT INTO DB2MON.HIS_MON_GET_BUFFERPOOL
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_BUFFERPOOL(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_CONNECTION
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_CONNECTION(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_CONNECTION_DETAILS
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_CONNECTION_DETAILS(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_CONTAINER
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_CONTAINER(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_INDEX
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_INDEX(NULL, NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_MEMORY_POOL
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_MEMORY_POOL(NULL, CURRENT_SERVER, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_MEMORY_SET
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_MEMORY_SET(NULL, CURRENT_SERVER, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_PKG_CACHE_STMT
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_PKG_CACHE_STMT(NULL,NULL,NULL,-2)) t;
INSERT INTO DB2MON.HIS_MON_GET_PKG_CACHE_STMT_DETAILS
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_PKG_CACHE_STMT_DETAILS(NULL,NULL,NULL,-2)) t;
INSERT INTO DB2MON.HIS_MON_GET_TABLE
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_TABLE(NULL, NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_TABLESPACE
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_TABLESPACE(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_WORKLOAD
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_WORKLOAD(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_GET_WORKLOAD_DETAILS
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(MON_GET_WORKLOAD_DETAILS(NULL, -2)) t;
INSERT INTO DB2MON.HIS_MON_PKG_CACHE_SUMMARY
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_PKG_CACHE_SUMMARY t;
INSERT INTO DB2MON.HIS_MON_TBSP_UTILIZATION
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_TBSP_UTILIZATION  t;
INSERT INTO DB2MON.HIS_MON_WORKLOAD_SUMMARY
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.MON_WORKLOAD_SUMMARY  t;
INSERT INTO DB2MON.HIS_LOG_UTILIZATION
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.LOG_UTILIZATION t;
INSERT INTO DB2MON.HIS_SNAPDB
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.SNAPDB t;
INSERT INTO DB2MON.HIS_SNAPTAB_REORG
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.SNAPTAB_REORG t;
INSERT INTO DB2MON.HIS_SNAPAPPL
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.SNAPAPPL  t;
INSERT INTO DB2MON.HIS_SNAPBP
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.SNAPBP  t;
INSERT INTO DB2MON.HIS_DB_HISTORY
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.DB_HISTORY  t;
INSERT INTO DB2MON.HIS_DBPATHS
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.DBPATHS  t;
INSERT INTO DB2MON.HIS_ADMIN_GET_DBP_MEM_USAGE
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from TABLE(ADMIN_GET_DBP_MEM_USAGE(NULL)) t;
INSERT INTO DB2MON.HIS_ADMINTABINFO
  select DB2MON.HIS_SNAPSHOT_TIMESTAMP as SNAPSHOT_TIME, t.* from SYSIBMADM.ADMINTABINFO t;


